services:
  prometheus:
    image: prom/prometheus:latest
    expose:
      - "9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring_net

  metric_service:
    build: 
      context: ./
    ports:
      - "8080:8080"                           # expose your Go app port
    restart: unless-stopped
    networks:
      - monitoring_net

networks:
  monitoring_net:
    driver: bridge